package webmail

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ConfigOptions struct {
	Domain       string
	DatabaseDSN  string
	IMAPHost     string
	IMAPPort     int
	SMTPHost     string
	SMTPPort     int
	DesKey       string
	WebmailRoot  string
	PHPSocket    string
	Plugins      []string
}

// GenerateRoundcubeConfig generates standard config.inc.php for Roundcube
func GenerateRoundcubeConfig(opts ConfigOptions) string {
	if opts.DatabaseDSN == "" {
		opts.DatabaseDSN = "sqlite:////var/lib/roundcube/db/sqlite.db?mode=0646"
	}
	if opts.IMAPHost == "" {
		opts.IMAPHost = "ssl://127.0.0.1"
	}
	if opts.IMAPPort == 0 {
		opts.IMAPPort = 993
	}
	if opts.SMTPHost == "" {
		opts.SMTPHost = "tls://127.0.0.1"
	}
	if opts.SMTPPort == 0 {
		opts.SMTPPort = 587
	}
	if opts.DesKey == "" {
		raw := make([]byte, 18)
		_, _ = rand.Read(raw)
		opts.DesKey = base64.RawURLEncoding.EncodeToString(raw)[:24]
	}

	plugins := opts.Plugins
	if len(plugins) == 0 {
		plugins = []string{"archive", "zipdownload", "managesieve"}
	}
	pluginList := "'" + strings.Join(plugins, "', '") + "'"

	return fmt.Sprintf(`<?php
// Hostvra Roundcube Webmail Production Configuration
// Auto-generated by Hostvra Agent. DO NOT EDIT DIRECTLY.

$config['db_dsnw'] = '%s';
$config['default_host'] = '%s';
$config['default_port'] = %d;
$config['smtp_server'] = '%s';
$config['smtp_port'] = %d;
$config['smtp_user'] = '%%u';
$config['smtp_pass'] = '%%p';
$config['smtp_auth_type'] = 'LOGIN';

// Security settings
$config['des_key'] = '%s';
$config['session_lifetime'] = 60;
$config['ip_check'] = true;
$config['enable_spellcheck'] = false;
$config['identities_level'] = 1;

// Product branding
$config['product_name'] = 'Hostvra Webmail';
$config['support_url'] = 'https://hostvra.com/support';

// Plugins
$config['plugins'] = [%s];
`, opts.DatabaseDSN, opts.IMAPHost, opts.IMAPPort, opts.SMTPHost, opts.SMTPPort, opts.DesKey, pluginList)
}

// GenerateWebmailNginxVHost creates Nginx server block for webmail.<domain>
func GenerateWebmailNginxVHost(opts ConfigOptions) string {
	domain := opts.Domain
	webmailHost := "webmail." + domain
	root := opts.WebmailRoot
	if root == "" {
		root = "/var/www/roundcube"
	}
	phpSock := opts.PHPSocket
	if phpSock == "" {
		phpSock = "unix:/run/php/php8.3-fpm.sock"
	}

	return fmt.Sprintf(`# Hostvra Webmail Nginx VHost for %s
server {
    listen 80;
    listen [::]:80;
    server_name %s;

    root %s;
    index index.php index.html;

    # Maximum attachment upload size
    client_max_body_size 50M;

    # Security Headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Deny access to sensitive files
    location ~ ^/(README|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
        deny all;
    }
    location ~ ^/(bin|config|logs|temp)/ {
        deny all;
    }
    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass %s;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }
}
`, webmailHost, webmailHost, root, phpSock)
}

// ApplyWebmailConfig writes Roundcube config file
func ApplyWebmailConfig(configDir string, opts ConfigOptions) error {
	if configDir == "" {
		configDir = "/etc/roundcube"
	}
	if err := os.MkdirAll(configDir, 0750); err != nil {
		return fmt.Errorf("failed to create roundcube config dir: %w", err)
	}

	confPath := filepath.Join(configDir, "config.inc.php")
	content := GenerateRoundcubeConfig(opts)
	return os.WriteFile(confPath, []byte(content), 0640)
}
