package nginx

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

var (
	validDomainRegex = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$`)
	validPHPRegex    = regexp.MustCompile(`^[0-9]\.[0-9]$`)
	ErrInvalidDomain = errors.New("invalid domain name format")
	ErrDirectiveInjection = errors.New("input contains forbidden control characters or Nginx directives")
)

type VHostConfig struct {
	Domain       string
	Aliases      []string
	DocumentRoot string
	AppType      string // "php", "static", "proxy"
	PHPVersion   string // e.g. "8.3"
	ProxyPort    int    // e.g. 3000
	SSLEnabled   bool
	CertPath     string
	KeyPath      string
}

const vhostTemplate = `# Hostvra Managed Virtual Host: {{ .Domain }}
# Auto-generated by Hostvra Engine. Do not edit manually.

server {
    listen 80;
    listen [::]:80;
    server_name {{ .Domain }}{{ range .Aliases }} {{ . }}{{ end }};

{{- if .SSLEnabled }}
    # Force HTTPS Redirect
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ .Domain }}{{ range .Aliases }} {{ . }}{{ end }};

    ssl_certificate {{ .CertPath }};
    ssl_certificate_key {{ .KeyPath }};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
{{- end }}

    root {{ .DocumentRoot }};
    index index.php index.html index.htm;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    access_log /var/log/nginx/{{ .Domain }}.access.log;
    error_log  /var/log/nginx/{{ .Domain }}.error.log warn;

    client_max_body_size 128M;

{{- if eq .AppType "php" }}
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php{{ .PHPVersion }}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
{{- else if eq .AppType "proxy" }}
    location / {
        proxy_pass http://127.0.0.1:{{ .ProxyPort }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
{{- else }}
    location / {
        try_files $uri $uri/ =404;
    }
{{- end }}

    location ~ /\.ht {
        deny all;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }
}
`

func sanitizeField(val string) error {
	if strings.ContainsAny(val, "\r\n;{}") {
		return ErrDirectiveInjection
	}
	return nil
}

func ValidateVHostConfig(cfg *VHostConfig) error {
	cfg.Domain = strings.ToLower(strings.TrimSpace(cfg.Domain))
	if !validDomainRegex.MatchString(cfg.Domain) || len(cfg.Domain) > 253 {
		return fmt.Errorf("%w: '%s'", ErrInvalidDomain, cfg.Domain)
	}

	for i, a := range cfg.Aliases {
		a = strings.ToLower(strings.TrimSpace(a))
		if !validDomainRegex.MatchString(a) || len(a) > 253 {
			return fmt.Errorf("%w alias: '%s'", ErrInvalidDomain, a)
		}
		cfg.Aliases[i] = a
	}

	if err := sanitizeField(cfg.DocumentRoot); err != nil {
		return fmt.Errorf("invalid document_root: %w", err)
	}
	cfg.DocumentRoot = filepath.Clean(cfg.DocumentRoot)

	if cfg.AppType == "proxy" {
		if cfg.ProxyPort < 1 || cfg.ProxyPort > 65535 {
			return errors.New("proxy_port must be between 1 and 65535")
		}
	} else if cfg.AppType == "php" {
		if cfg.PHPVersion == "" {
			cfg.PHPVersion = "8.3"
		}
		if !validPHPRegex.MatchString(cfg.PHPVersion) {
			return errors.New("invalid php_version format (e.g. '8.3')")
		}
	}

	if cfg.SSLEnabled {
		if err := sanitizeField(cfg.CertPath); err != nil {
			return fmt.Errorf("invalid cert_path: %w", err)
		}
		if err := sanitizeField(cfg.KeyPath); err != nil {
			return fmt.Errorf("invalid key_path: %w", err)
		}
	}

	return nil
}

func GenerateVHost(cfg VHostConfig) (string, error) {
	if err := ValidateVHostConfig(&cfg); err != nil {
		return "", err
	}

	tmpl, err := template.New("vhost").Parse(vhostTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse vhost template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("failed to render vhost template: %w", err)
	}

	return buf.String(), nil
}
