package nginx

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

type VHostConfig struct {
	Domain       string
	Aliases      []string
	DocumentRoot string
	AppType      string // "php", "static", "proxy"
	PHPVersion   string // e.g. "8.3"
	ProxyPort    int    // e.g. 3000
	SSLEnabled   bool
	CertPath     string
	KeyPath      string
}

const vhostTemplate = `# Hostvra Managed Virtual Host: {{ .Domain }}
# Auto-generated by Hostvra Engine. Do not edit manually.

server {
    listen 80;
    listen [::]:80;
    server_name {{ .Domain }}{{ range .Aliases }} {{ . }}{{ end }};

{{- if .SSLEnabled }}
    # Force HTTPS Redirect
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ .Domain }}{{ range .Aliases }} {{ . }}{{ end }};

    ssl_certificate {{ .CertPath }};
    ssl_certificate_key {{ .KeyPath }};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
{{- end }}

    root {{ .DocumentRoot }};
    index index.php index.html index.htm;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    access_log /var/log/nginx/{{ .Domain }}.access.log;
    error_log  /var/log/nginx/{{ .Domain }}.error.log warn;

    client_max_body_size 128M;

{{- if eq .AppType "php" }}
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php{{ .PHPVersion }}-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }
{{- else if eq .AppType "proxy" }}
    location / {
        proxy_pass http://127.0.0.1:{{ .ProxyPort }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
{{- else }}
    location / {
        try_files $uri $uri/ =404;
    }
{{- end }}

    location ~ /\.ht {
        deny all;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }
}
`

func GenerateVHost(cfg VHostConfig) (string, error) {
	if cfg.PHPVersion == "" {
		cfg.PHPVersion = "8.3"
	}
	cfg.Domain = strings.TrimSpace(cfg.Domain)

	tmpl, err := template.New("vhost").Parse(vhostTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse vhost template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("failed to render vhost template: %w", err)
	}

	return buf.String(), nil
}
