package php

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// PoolConfigParams defines parameters for generating an isolated PHP-FPM pool configuration
type PoolConfigParams struct {
	PoolName                string            `json:"pool_name"` // e.g. "hostvra-example-com"
	Version                 string            `json:"version"`   // e.g. "8.3"
	SocketPath              string            `json:"socket_path"`
	User                    string            `json:"user"`
	Group                   string            `json:"group"`
	ListenOwner             string            `json:"listen_owner"`
	ListenGroup             string            `json:"listen_group"`
	PMType                  string            `json:"pm_type"` // dynamic, ondemand, static
	PMMaxChildren           int               `json:"pm_max_children"`
	PMStartServers          int               `json:"pm_start_servers"`
	PMMinSpareServers       int               `json:"pm_min_spare_servers"`
	PMMaxSpareServers       int               `json:"pm_max_spare_servers"`
	PMMaxRequests           int               `json:"pm_max_requests"`
	RequestTerminateTimeout int               `json:"request_terminate_timeout"`
	RequestSlowlogTimeout   int               `json:"request_slowlog_timeout"`
	SlowlogPath             string            `json:"slowlog_path"`
	AdminValues             map[string]string `json:"admin_values,omitempty"`
	AdminFlags              map[string]string `json:"admin_flags,omitempty"`
}

// PoolManager handles isolated PHP-FPM pool configuration lifecycle
type PoolManager struct {
	txMgr *TransactionManager
}

// NewPoolManager creates a new PoolManager
func NewPoolManager() *PoolManager {
	return &PoolManager{
		txMgr: NewTransactionManager(),
	}
}

const poolTemplate = `; ==============================================================================
; Hostvra Managed PHP-FPM Pool: {{.PoolName}}
; Generated by Hostvra Engine for isolated website hosting
; ==============================================================================

[{{.PoolName}}]
user = {{.User}}
group = {{.Group}}

listen = {{.SocketPath}}
listen.owner = {{.ListenOwner}}
listen.group = {{.ListenGroup}}
listen.mode = 0660

pm = {{.PMType}}
pm.max_children = {{.PMMaxChildren}}
{{- if eq .PMType "dynamic"}}
pm.start_servers = {{.PMStartServers}}
pm.min_spare_servers = {{.PMMinSpareServers}}
pm.max_spare_servers = {{.PMMaxSpareServers}}
{{- end}}
pm.max_requests = {{.PMMaxRequests}}

request_terminate_timeout = {{.RequestTerminateTimeout}}s
{{- if gt .RequestSlowlogTimeout 0}}
request_slowlog_timeout = {{.RequestSlowlogTimeout}}s
slowlog = {{.SlowlogPath}}
{{- end}}

catch_workers_output = yes
decorate_workers_output = no

; Hostvra Per-Site Overrides
{{- range $key, $val := .AdminValues}}
php_admin_value[{{$key}}] = {{$val}}
{{- end}}
{{- range $key, $val := .AdminFlags}}
php_admin_flag[{{$key}}] = {{$val}}
{{- end}}
`

// GeneratePoolConfig generates PHP-FPM INI format pool configuration string
func (p *PoolManager) GeneratePoolConfig(params PoolConfigParams) (string, error) {
	if params.User == "" {
		params.User = "www-data"
	}
	if params.Group == "" {
		params.Group = "www-data"
	}
	if params.ListenOwner == "" {
		params.ListenOwner = "www-data"
	}
	if params.ListenGroup == "" {
		params.ListenGroup = "www-data"
	}
	if params.PMType == "" {
		params.PMType = "dynamic"
	}
	if params.PMMaxChildren <= 0 {
		params.PMMaxChildren = 10
	}
	if params.PMStartServers <= 0 {
		params.PMStartServers = 2
	}
	if params.PMMinSpareServers <= 0 {
		params.PMMinSpareServers = 2
	}
	if params.PMMaxSpareServers <= 0 {
		params.PMMaxSpareServers = 4
	}
	if params.PMMaxRequests <= 0 {
		params.PMMaxRequests = 500
	}
	if params.RequestTerminateTimeout <= 0 {
		params.RequestTerminateTimeout = 120
	}
	if params.SlowlogPath == "" {
		params.SlowlogPath = fmt.Sprintf("/var/log/php-fpm/%s-slow.log", params.PoolName)
	}

	tmpl, err := template.New("fpm_pool").Parse(poolTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// WritePoolConfig stages and atomically writes an isolated pool file with syntax validation and rollback
func (p *PoolManager) WritePoolConfig(ctx context.Context, params PoolConfigParams) (*TransactionResult, error) {
	content, err := p.GeneratePoolConfig(params)
	if err != nil {
		return nil, err
	}

	poolDir := fmt.Sprintf("/etc/php/%s/fpm/pool.d", params.Version)
	if _, err := os.Stat(poolDir); err != nil {
		poolDir = fmt.Sprintf("/etc/opt/remi/php%s/php-fpm.d", strings.ReplaceAll(params.Version, ".", ""))
	}
	_ = os.MkdirAll(poolDir, 0755)

	targetFile := filepath.Join(poolDir, fmt.Sprintf("%s.conf", params.PoolName))
	serviceName := fmt.Sprintf("php%s-fpm", params.Version)

	return p.txMgr.ExecuteAtomicWrite(ctx, params.Version, targetFile, content, serviceName)
}

// DeletePoolConfig safely removes an isolated pool and reloads PHP-FPM
func (p *PoolManager) DeletePoolConfig(ctx context.Context, version string, poolName string) error {
	poolDir := fmt.Sprintf("/etc/php/%s/fpm/pool.d", version)
	targetFile := filepath.Join(poolDir, fmt.Sprintf("%s.conf", poolName))

	if _, err := os.Stat(targetFile); os.IsNotExist(err) {
		return nil
	}

	if err := os.Remove(targetFile); err != nil {
		return fmt.Errorf("failed to delete pool file %s: %w", targetFile, err)
	}

	fpm := NewFPMManager()
	_ = fpm.ReloadService(ctx, version)
	return nil
}
