package dovecot

import (
	"crypto/rand"
	"crypto/sha512"
	"encoding/base64"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type ConfigOptions struct {
	MailDirBase string // e.g. "/var/mail/vhosts"
	VmailUID    int    // default 5000
	VmailGID    int    // default 5000
	SSLCertPath string // e.g. "/etc/letsencrypt/live/mail.example.com/fullchain.pem"
	SSLKeyPath  string // e.g. "/etc/letsencrypt/live/mail.example.com/privkey.pem"
}

type UserAccount struct {
	Email        string // "user@example.com"
	PasswordHash string // "{SHA512-CRYPT}$6$rounds=50000$..." or raw hash
	Domain       string // "example.com"
	LocalPart    string // "user"
	QuotaBytes   int64  // e.g. 5368709120
}

// GenerateDovecotConf creates main dovecot.conf
func GenerateDovecotConf() string {
	return `# Hostvra Production Dovecot Configuration
# Auto-generated by Hostvra Agent. DO NOT EDIT DIRECTLY.
protocols = imap pop3 lmtp
listen = *, ::
base_dir = /var/run/dovecot/
!include conf.d/*.conf
`
}

// GenerateMailConf creates 10-mail.conf
func GenerateMailConf(opts ConfigOptions) string {
	if opts.MailDirBase == "" {
		opts.MailDirBase = "/var/mail/vhosts"
	}
	if opts.VmailUID == 0 {
		opts.VmailUID = 5000
	}
	if opts.VmailGID == 0 {
		opts.VmailGID = 5000
	}

	return fmt.Sprintf(`# Hostvra Dovecot 10-mail.conf
mail_location = maildir:%s/%%d/%%n
mail_uid = %d
mail_gid = %d
mail_privileged_group = mail

namespace inbox {
  inbox = yes

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
}
`, opts.MailDirBase, opts.VmailUID, opts.VmailGID)
}

// GenerateAuthConf creates 10-auth.conf
func GenerateAuthConf() string {
	return `# Hostvra Dovecot 10-auth.conf
disable_plaintext_auth = yes
auth_mechanisms = plain login
!include auth-passwdfile.conf.ext
`
}

// GenerateAuthPasswdFileConf creates auth-passwdfile.conf.ext
func GenerateAuthPasswdFileConf(passwdPath string) string {
	if passwdPath == "" {
		passwdPath = "/etc/dovecot/users"
	}
	return fmt.Sprintf(`# Hostvra Dovecot auth-passwdfile.conf.ext
passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%%u %s
}

userdb {
  driver = passwd-file
  args = username_format=%%u %s
}
`, passwdPath, passwdPath)
}

// GenerateSSLConf creates 10-ssl.conf
func GenerateSSLConf(opts ConfigOptions) string {
	cert := opts.SSLCertPath
	key := opts.SSLKeyPath
	if cert == "" {
		cert = "/etc/ssl/certs/ssl-cert-snakeoil.pem"
	}
	if key == "" {
		key = "/etc/ssl/private/ssl-cert-snakeoil.key"
	}

	return fmt.Sprintf(`# Hostvra Dovecot 10-ssl.conf
ssl = required
ssl_cert = <%s
ssl_key = <%s
ssl_min_protocol = TLSv1.2
ssl_cipher_list = HIGH:!aNULL:!MD5:!RC4:!3DES:!SEED:!IDEA
ssl_prefer_server_ciphers = yes
`, cert, key)
}

// GenerateMasterConf creates 10-master.conf with LMTP and Postfix SASL sockets
func GenerateMasterConf() string {
	return `# Hostvra Dovecot 10-master.conf
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }
}

service auth-worker {
  user = root
}
`
}

// GenerateUsersFile builds the Dovecot virtual passwd-file content
func GenerateUsersFile(accounts []UserAccount, opts ConfigOptions) string {
	if opts.MailDirBase == "" {
		opts.MailDirBase = "/var/mail/vhosts"
	}
	if opts.VmailUID == 0 {
		opts.VmailUID = 5000
	}
	if opts.VmailGID == 0 {
		opts.VmailGID = 5000
	}

	var sb strings.Builder
	for _, acc := range accounts {
		hash := acc.PasswordHash
		if !strings.HasPrefix(hash, "{") {
			hash = "{SHA512-CRYPT}" + hash
		}
		quotaMB := acc.QuotaBytes / (1024 * 1024)
		if quotaMB <= 0 {
			quotaMB = 5120 // 5GB default
		}
		homeDir := fmt.Sprintf("%s/%s/%s", opts.MailDirBase, acc.Domain, acc.LocalPart)

		// Format: email:hash:uid:gid::home::userdb_quota_rule=*:storage=Xm
		sb.WriteString(fmt.Sprintf("%s:%s:%d:%d::%s::userdb_quota_rule=*:storage=%dM\n",
			acc.Email, hash, opts.VmailUID, opts.VmailGID, homeDir, quotaMB))
	}
	return sb.String()
}

// HashPassword generates a secure SHA512 password hash for Dovecot passwd-file
func HashPassword(plainPassword string) string {
	saltBytes := make([]byte, 12)
	_, _ = rand.Read(saltBytes)
	salt := base64.RawStdEncoding.EncodeToString(saltBytes)[:16]

	h := sha512.New()
	h.Write([]byte(plainPassword + salt))
	hashHex := fmt.Sprintf("%x", h.Sum(nil))

	return fmt.Sprintf("$6$%s$%s", salt, hashHex)
}

// ApplyDovecotConfig writes config files and users map, then reloads Dovecot safely
func ApplyDovecotConfig(configDir string, opts ConfigOptions, accounts []UserAccount) error {
	if configDir == "" {
		configDir = "/etc/dovecot"
	}
	confD := filepath.Join(configDir, "conf.d")
	if err := os.MkdirAll(confD, 0755); err != nil {
		return fmt.Errorf("failed to create dovecot conf.d: %w", err)
	}

	files := map[string]string{
		filepath.Join(configDir, "dovecot.conf"):                 GenerateDovecotConf(),
		filepath.Join(confD, "10-mail.conf"):                     GenerateMailConf(opts),
		filepath.Join(confD, "10-auth.conf"):                     GenerateAuthConf(),
		filepath.Join(confD, "auth-passwdfile.conf.ext"):         GenerateAuthPasswdFileConf(filepath.Join(configDir, "users")),
		filepath.Join(confD, "10-ssl.conf"):                      GenerateSSLConf(opts),
		filepath.Join(confD, "10-master.conf"):                   GenerateMasterConf(),
		filepath.Join(configDir, "users"):                        GenerateUsersFile(accounts, opts),
	}

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0640); err != nil {
			return fmt.Errorf("failed to write %s: %w", path, err)
		}
	}

	// Reload Dovecot if running
	if _, err := exec.LookPath("doveadm"); err == nil {
		_ = exec.Command("doveadm", "reload").Run()
	}

	return nil
}
