package dovecot

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"golang.org/x/crypto/bcrypt"
)

type ConfigOptions struct {
	MailDirBase string // e.g. "/var/mail/vhosts"
	VmailUID    int    // default 5000
	VmailGID    int    // default 5000
	SSLCertPath string // e.g. "/etc/letsencrypt/live/mail.example.com/fullchain.pem"
	SSLKeyPath  string // e.g. "/etc/letsencrypt/live/mail.example.com/privkey.pem"
	ConfigDir   string // e.g. "/etc/dovecot"
}

type UserAccount struct {
	Email        string // "user@example.com"
	PasswordHash string // "{SHA512-CRYPT}$6$rounds=50000$..." or raw hash
	Domain       string // "example.com"
	LocalPart    string // "user"
	QuotaBytes   int64  // e.g. 5368709120
}

func isDovecot24() bool {
	if out, err := exec.Command("dovecot", "--version").Output(); err == nil {
		return strings.HasPrefix(strings.TrimSpace(string(out)), "2.4")
	}
	return false
}

// GenerateDovecotConf creates main dovecot.conf
func GenerateDovecotConf() string {
	versionHeader := ""
	if isDovecot24() {
		versionHeader = "dovecot_config_version = 2.4.0\ndovecot_storage_version = 2.4.0\n\n"
	}
	return fmt.Sprintf(`# Hostvra Production Dovecot Configuration
# Auto-generated by Hostvra Agent. DO NOT EDIT DIRECTLY.
%sprotocols = imap pop3 lmtp
listen = *, ::
base_dir = /var/run/dovecot/
!include conf.d/*.conf
`, versionHeader)
}

// GenerateMailConf creates 10-mail.conf
func GenerateMailConf(opts ConfigOptions) string {
	if opts.MailDirBase == "" {
		opts.MailDirBase = "/var/mail/vhosts"
	}
	if opts.VmailUID == 0 {
		opts.VmailUID = 5000
	}
	if opts.VmailGID == 0 {
		opts.VmailGID = 5000
	}

	mailDirective := fmt.Sprintf("mail_location = maildir:%s/%%d/%%n", opts.MailDirBase)
	if isDovecot24() {
		mailDirective = fmt.Sprintf("mail_driver = maildir\nmail_home = %s/%%%%{user | domain}/%%%%{user | username}\nmail_path = ~/", opts.MailDirBase)
	}

	return fmt.Sprintf(`# Hostvra Dovecot 10-mail.conf
%s
mail_uid = %d
mail_gid = %d
mail_privileged_group = mail

namespace inbox {
  inbox = yes

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
}
`, mailDirective, opts.VmailUID, opts.VmailGID)
}

// GenerateAuthConf creates 10-auth.conf
func GenerateAuthConf() string {
	cleartextDirective := "disable_plaintext_auth = yes"
	usernameFormat := "auth_username_format = %u"
	if isDovecot24() {
		cleartextDirective = "auth_allow_cleartext = yes"
		usernameFormat = "auth_username_format = %{user|lower}"
	}
	return fmt.Sprintf(`# Hostvra Dovecot 10-auth.conf
%s
%s
auth_mechanisms = plain login
!include auth-passwdfile.conf.ext
`, cleartextDirective, usernameFormat)
}

// GenerateAuthPasswdFileConf creates auth-passwdfile.conf.ext
func GenerateAuthPasswdFileConf(passwdPath string) string {
	if passwdPath == "" {
		passwdPath = "/etc/dovecot/users"
	}

	if isDovecot24() {
		return fmt.Sprintf(`# Hostvra Dovecot auth-passwdfile.conf.ext (Dovecot 2.4+)
passdb passwd-file {
  passwd_file_path = %s
}

userdb passwd-file {
  passwd_file_path = %s
}
`, passwdPath, passwdPath)
	}

	return fmt.Sprintf(`# Hostvra Dovecot auth-passwdfile.conf.ext (Dovecot 2.3)
passdb passwd-file {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%%%%u %s
}

userdb passwd-file {
  driver = passwd-file
  args = username_format=%%%%u %s
}
`, passwdPath, passwdPath)
}

// GenerateSSLConf creates 10-ssl.conf
func GenerateSSLConf(opts ConfigOptions) string {
	cert := opts.SSLCertPath
	key := opts.SSLKeyPath
	if cert == "" {
		cert = "/etc/ssl/certs/ssl-cert-snakeoil.pem"
	}
	if key == "" {
		key = "/etc/ssl/private/ssl-cert-snakeoil.key"
	}

	if isDovecot24() {
		return fmt.Sprintf(`# Hostvra Dovecot 10-ssl.conf (Dovecot 2.4+)
ssl = required
ssl_server_cert_file = %s
ssl_server_key_file = %s
ssl_min_protocol = TLSv1.2
`, cert, key)
	}

	return fmt.Sprintf(`# Hostvra Dovecot 10-ssl.conf (Dovecot 2.3)
ssl = required
ssl_cert = <%s
ssl_key = <%s
ssl_min_protocol = TLSv1.2
ssl_cipher_list = HIGH:!aNULL:!MD5:!RC4:!3DES:!SEED:!IDEA
ssl_prefer_server_ciphers = yes
`, cert, key)
}

// GenerateMasterConf creates 10-master.conf with LMTP and Postfix SASL sockets
func GenerateMasterConf() string {
	return `# Hostvra Dovecot 10-master.conf
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service auth {
  extra_groups = vmail
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0666
  }
}

service auth-worker {
  user = root
  extra_groups = vmail
}
`
}

// GenerateUsersFile builds the Dovecot virtual passwd-file content.
// It merges new accounts while protecting existing accounts against blank/corrupted password hashes.
func GenerateUsersFile(accounts []UserAccount, opts ConfigOptions) string {
	if opts.MailDirBase == "" {
		opts.MailDirBase = "/var/mail/vhosts"
	}
	if opts.VmailUID == 0 {
		opts.VmailUID = 5000
	}
	if opts.VmailGID == 0 {
		opts.VmailGID = 5000
	}

	configDir := opts.ConfigDir
	if configDir == "" {
		configDir = "/etc/dovecot"
	}

	// 1. Read existing valid hashes from disk to protect against blank hash overwrite
	existingHashes := make(map[string]string)
	usersFile := filepath.Join(configDir, "users")
	if data, err := os.ReadFile(usersFile); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.Split(line, ":")
			if len(parts) >= 2 {
				email := strings.ToLower(strings.TrimSpace(parts[0]))
				hash := strings.TrimSpace(parts[1])
				if hash != "" && hash != "{CRYPT}:" && hash != "{CRYPT}" {
					existingHashes[email] = hash
				}
			}
		}
	}

	var sb strings.Builder
	for _, acc := range accounts {
		emailKey := strings.ToLower(strings.TrimSpace(acc.Email))
		hash := strings.TrimSpace(acc.PasswordHash)

		// Empty hash protection: retain existing valid hash if available, otherwise safely reject/skip
		if hash == "" {
			if existing, ok := existingHashes[emailKey]; ok && existing != "" {
				hash = existing
			} else {
				// Safely skip: never write empty or {CRYPT}: password entry
				continue
			}
		}

		if !strings.HasPrefix(hash, "{") {
			if strings.HasPrefix(hash, "$2a$") || strings.HasPrefix(hash, "$2b$") || strings.HasPrefix(hash, "$2y$") {
				hash = "{BLF-CRYPT}" + hash
			} else if strings.HasPrefix(hash, "$6$") {
				hash = "{SHA512-CRYPT}" + hash
			} else {
				hash = "{CRYPT}" + hash
			}
		}
		quotaMB := acc.QuotaBytes / (1024 * 1024)
		if quotaMB <= 0 {
			quotaMB = 5120 // 5GB default
		}
		homeDir := fmt.Sprintf("%s/%s/%s", opts.MailDirBase, acc.Domain, acc.LocalPart)

		// Format: email:hash:uid:gid::home::userdb_quota_rule=*:storage=Xm
		sb.WriteString(fmt.Sprintf("%s:%s:%d:%d::%s::userdb_quota_rule=*:storage=%dM\n",
			acc.Email, hash, opts.VmailUID, opts.VmailGID, homeDir, quotaMB))
	}
	return sb.String()
}

// HashPassword generates a secure, Dovecot-compatible password hash without exposing plain password in process arguments
func HashPassword(plainPassword string) string {
	if plainPassword == "" {
		return ""
	}

	// 1. If doveadm is available on the system, use native SHA512-CRYPT via stdin (avoiding -p argument in ps/proc)
	if doveadmPath, err := exec.LookPath("doveadm"); err == nil {
		cmd := exec.Command(doveadmPath, "pw", "-s", "SHA512-CRYPT")
		cmd.Stdin = strings.NewReader(plainPassword + "\n" + plainPassword + "\n")
		if out, err := cmd.Output(); err == nil {
			trimmed := strings.TrimSpace(string(out))
			if trimmed != "" {
				return trimmed
			}
		}
	}

	// 2. Standard cryptographically secure fallback: BLF-CRYPT (bcrypt) which Dovecot natively supports in-process
	hash, err := bcrypt.GenerateFromPassword([]byte(plainPassword), 10)
	if err == nil {
		return "{BLF-CRYPT}" + string(hash)
	}

	return ""
}

// ApplyDovecotConfig writes config files and users map, then reloads Dovecot safely
func ApplyDovecotConfig(configDir string, opts ConfigOptions, accounts []UserAccount) error {
	if configDir == "" {
		configDir = "/etc/dovecot"
	}
	opts.ConfigDir = configDir
	confD := filepath.Join(configDir, "conf.d")
	if err := os.MkdirAll(confD, 0755); err != nil {
		return fmt.Errorf("failed to create dovecot conf.d: %w", err)
	}

	files := map[string]string{
		filepath.Join(configDir, "dovecot.conf"):                 GenerateDovecotConf(),
		filepath.Join(confD, "10-mail.conf"):                     GenerateMailConf(opts),
		filepath.Join(confD, "10-auth.conf"):                     GenerateAuthConf(),
		filepath.Join(confD, "auth-passwdfile.conf.ext"):         GenerateAuthPasswdFileConf(filepath.Join(configDir, "users")),
		filepath.Join(confD, "10-ssl.conf"):                      GenerateSSLConf(opts),
		filepath.Join(confD, "10-master.conf"):                   GenerateMasterConf(),
		filepath.Join(configDir, "users"):                        GenerateUsersFile(accounts, opts),
	}

	for path, content := range files {
		perm := os.FileMode(0644)
		if strings.HasSuffix(path, ".key") {
			perm = 0600
		}
		if err := os.WriteFile(path, []byte(content), perm); err != nil {
			return fmt.Errorf("failed to write %s: %w", path, err)
		}
	}

	// Reload Dovecot & Postfix
	_ = exec.Command("systemctl", "reload", "dovecot").Run()
	_ = exec.Command("systemctl", "reload", "postfix").Run()
	if _, err := exec.LookPath("doveadm"); err == nil {
		_ = exec.Command("doveadm", "reload").Run()
	}

	return nil
}
