package postfix

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type ConfigOptions struct {
	Hostname         string // e.g. "mail.hostvra.com"
	Domain           string // e.g. "hostvra.com"
	MailDirBase      string // default "/var/mail/vhosts"
	VmailUID         int    // default 5000
	VmailGID         int    // default 5000
	SSLCertPath      string // e.g. "/etc/letsencrypt/live/mail.hostvra.com/fullchain.pem"
	SSLKeyPath       string // e.g. "/etc/letsencrypt/live/mail.hostvra.com/privkey.pem"
	EnableRspamd     bool   // default true
	RspamdMilterAddr string // default "inet:127.0.0.1:11332"
}

type VirtualDomain struct {
	Domain string
}

type VirtualMailbox struct {
	Email    string // "user@example.com"
	MailPath string // "example.com/user/"
}

type VirtualAlias struct {
	SourceAddress      string // "support@example.com"
	DestinationAddress string // "user@example.com"
}

// GenerateMainCF builds production postfix main.cf with strict anti-open-relay rules
func GenerateMainCF(opts ConfigOptions) string {
	if opts.MailDirBase == "" {
		opts.MailDirBase = "/var/mail/vhosts"
	}
	if opts.VmailUID == 0 {
		opts.VmailUID = 5000
	}
	if opts.VmailGID == 0 {
		opts.VmailGID = 5000
	}
	if opts.RspamdMilterAddr == "" {
		opts.RspamdMilterAddr = "inet:127.0.0.1:11332"
	}

	var sb strings.Builder
	sb.WriteString("# Hostvra Production Postfix Configuration (main.cf)\n")
	sb.WriteString("# Auto-generated by Hostvra Agent. DO NOT EDIT DIRECTLY.\n\n")

	sb.WriteString(fmt.Sprintf("myhostname = %s\n", opts.Hostname))
	sb.WriteString(fmt.Sprintf("mydomain = %s\n", opts.Domain))
	sb.WriteString("myorigin = $mydomain\n")
	sb.WriteString("inet_interfaces = all\n")
	sb.WriteString("inet_protocols = ipv4\n")
	sb.WriteString("mydestination = localhost.$mydomain, localhost\n\n")

	// TLS Security
	sb.WriteString("# TLS & Encryption Policies\n")
	sb.WriteString("smtpd_tls_security_level = may\n")
	sb.WriteString("smtp_tls_security_level = dane\n")
	sb.WriteString("smtp_dns_support_level = dnssec\n")
	sb.WriteString("smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1\n")
	sb.WriteString("smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1\n")
	sb.WriteString("smtpd_tls_ciphers = high\n")
	sb.WriteString("smtpd_tls_mandatory_ciphers = high\n")
	sb.WriteString("smtpd_tls_exclude_ciphers = aNULL, MD5, DES, 3DES, DES-CBC3-SHA, RC4, SEED, IDEA\n")
	sb.WriteString("smtpd_tls_auth_only = yes\n")
	if opts.SSLCertPath != "" && opts.SSLKeyPath != "" {
		sb.WriteString(fmt.Sprintf("smtpd_tls_cert_file = %s\n", opts.SSLCertPath))
		sb.WriteString(fmt.Sprintf("smtpd_tls_key_file = %s\n", opts.SSLKeyPath))
	}

	// SASL Authentication (Dovecot backend)
	sb.WriteString("\n# SASL Authentication via Dovecot\n")
	sb.WriteString("smtpd_sasl_type = dovecot\n")
	sb.WriteString("smtpd_sasl_path = private/auth\n")
	sb.WriteString("smtpd_sasl_auth_enable = yes\n")
	sb.WriteString("smtpd_sasl_security_options = noanonymous\n")
	sb.WriteString("smtpd_sasl_local_domain = $myhostname\n")
	sb.WriteString("broken_sasl_auth_clients = yes\n\n")

	// STRICT ANTI-OPEN-RELAY RESTRICTIONS (Crucial Requirement)
	sb.WriteString("# Strict Relay & Recipient Restrictions (Zero Open Relay)\n")
	sb.WriteString("smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination\n")
	sb.WriteString("smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_non_fqdn_recipient, reject_unknown_recipient_domain\n")
	sb.WriteString("smtpd_sender_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_non_fqdn_sender, reject_unknown_sender_domain\n")
	sb.WriteString("smtpd_helo_required = yes\n")
	sb.WriteString("smtpd_helo_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname\n\n")

	// Virtual Domain & Mailbox Maps
	sb.WriteString("# Virtual Mailbox & Aliases Configuration\n")
	sb.WriteString("virtual_mailbox_domains = hash:/etc/postfix/vdomains\n")
	sb.WriteString("virtual_mailbox_base = " + opts.MailDirBase + "\n")
	sb.WriteString("virtual_mailbox_maps = hash:/etc/postfix/vmailbox\n")
	sb.WriteString("virtual_alias_maps = hash:/etc/postfix/valias\n")
	sb.WriteString(fmt.Sprintf("virtual_uid_maps = static:%d\n", opts.VmailUID))
	sb.WriteString(fmt.Sprintf("virtual_gid_maps = static:%d\n", opts.VmailGID))
	sb.WriteString("virtual_transport = lmtp:unix:private/dovecot-lmtp\n\n")

	// Size & Queue Limits
	sb.WriteString("# Message & Quota Limits\n")
	sb.WriteString("message_size_limit = 52428800\n") // 50 MB
	sb.WriteString("mailbox_size_limit = 0\n")        // Handled by Dovecot quota
	sb.WriteString("smtpd_recipient_limit = 50\n\n")

	// Rspamd Milter
	if opts.EnableRspamd {
		sb.WriteString("# Rspamd Milter Integration (Spam, DKIM, DMARC)\n")
		sb.WriteString(fmt.Sprintf("smtpd_milters = %s\n", opts.RspamdMilterAddr))
		sb.WriteString(fmt.Sprintf("non_smtpd_milters = %s\n", opts.RspamdMilterAddr))
		sb.WriteString("milter_default_action = accept\n")
		sb.WriteString("milter_protocol = 6\n\n")
	}

	return sb.String()
}

// GenerateMasterCF generates production master.cf with submission (587) and smtps (465)
func GenerateMasterCF() string {
	return `# Hostvra Production Postfix Master Process Configuration (master.cf)
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
smtp      inet  n       -       y       -       -       smtpd
  -o smtpd_milters=inet:127.0.0.1:11332

# Submission (Port 587) for Authenticated Mail Clients
submission inet n       -       y       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_tls_auth_only=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

# SMTPS (Port 465) with Implicit TLS
smtps     inet  n       -       y       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
`
}

// GenerateVirtualDomains generates the vdomains file content
func GenerateVirtualDomains(domains []VirtualDomain) string {
	var sb strings.Builder
	for _, d := range domains {
		sb.WriteString(fmt.Sprintf("%s OK\n", d.Domain))
	}
	return sb.String()
}

// GenerateVirtualMailboxes generates the vmailbox map content
func GenerateVirtualMailboxes(mailboxes []VirtualMailbox) string {
	var sb strings.Builder
	for _, mb := range mailboxes {
		sb.WriteString(fmt.Sprintf("%s %s\n", mb.Email, mb.MailPath))
	}
	return sb.String()
}

// GenerateVirtualAliases generates the valias map content
func GenerateVirtualAliases(aliases []VirtualAlias) string {
	var sb strings.Builder
	for _, a := range aliases {
		sb.WriteString(fmt.Sprintf("%s %s\n", a.SourceAddress, a.DestinationAddress))
	}
	return sb.String()
}

// ApplyMaps writes map files and invokes postmap with atomic rollback protection
func ApplyMaps(configDir string, domains []VirtualDomain, mailboxes []VirtualMailbox, aliases []VirtualAlias) error {
	if configDir == "" {
		configDir = "/etc/postfix"
	}
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create postfix config directory: %w", err)
	}

	files := map[string]string{
		"vdomains": GenerateVirtualDomains(domains),
		"vmailbox": GenerateVirtualMailboxes(mailboxes),
		"valias":   GenerateVirtualAliases(aliases),
	}

	for fname, content := range files {
		targetPath := filepath.Join(configDir, fname)
		if err := os.WriteFile(targetPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", fname, err)
		}

		// Run postmap if postmap executable is present on the machine
		if _, err := exec.LookPath("postmap"); err == nil {
			cmd := exec.Command("postmap", targetPath)
			if out, err := cmd.CombinedOutput(); err != nil {
				return fmt.Errorf("postmap failed for %s: %s (%w)", fname, string(out), err)
			}
		}
	}

	// Reload postfix if running
	if _, err := exec.LookPath("postfix"); err == nil {
		_ = exec.Command("postfix", "reload").Run()
	}

	return nil
}
